package prow

import (
	"bytes"
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	OwnersAliasesFilename = "OWNERS_ALIASES"
	FileHeader            = `
# This file was automatically generated by prow-aliases-syncer. DO NOT EDIT.
# To change team associations, update the GitHub teams via https://github.com/kubermatic/access.
`
)

type OwnersAliases struct {
	Aliases map[string][]string
}

func FromString(data string) (*OwnersAliases, error) {
	result := &OwnersAliases{}

	if err := yaml.Unmarshal([]byte(data), result); err != nil {
		return nil, err
	}

	return result, nil
}

func FromFile(filename string) (*OwnersAliases, error) {
	content, err := os.ReadFile(filename)
	if err != nil {
		return nil, err
	}

	return FromString(string(content))
}

func (oa *OwnersAliases) ToYAML() (string, error) {
	var buf bytes.Buffer

	encoder := yaml.NewEncoder(&buf)
	encoder.SetIndent(2)

	if err := encoder.Encode(oa); err != nil {
		return "", nil
	}

	return fmt.Sprintf("%s\n\n%s", strings.TrimSpace(FileHeader), buf.String()), nil
}

func (os *OwnersAliases) Sort() {
	for team, members := range os.Aliases {
		sort.Strings(members)
		os.Aliases[team] = members
	}
}
